#!/bin/bash

# https://gist.github.com/martijnvermaat/8070533
# https://werat.github.io/2017/02/04/tmux-ssh-agent-forwarding.html
if test "$SSH_AUTH_SOCK" ; then
   ln -sf $SSH_AUTH_SOCK ~/.ssh/ssh_auth_sock
fi
