#!/bin/bash

brew install ack
brew install android-platform-tools
brew install ant
brew install astyle
brew install brew-cask
brew install cloc
brew install ctags
brew install git
brew install gnupg
brew install go
brew install heroku-toolbelt
brew install horndis
brew install htop-osx
brew install httperf
brew install icdiff
brew install mercurial
brew install namebench
brew install ngrep
brew install nmap
brew install node
brew install ntfs-3g
brew install osxfuse
brew install python
brew install python3
brew install sqlite
brew install sshfs
brew install tmux
brew install tree
brew install vim
brew install wget
brew install zsh

