#!/bin/bash

brew install go
brew install python
brew install ack
brew install ctags
brew install git
brew install mercurial
brew install wget
brew install vim
brew install tree
brew install osxfuse
brew install sshfs
brew install ntfs-3g
brew install zsh
brew install tmux
brew install gpg
brew install ant
brew install astyle
