#!/bin/bash

brew cask install android-studio
brew cask install appcleaner
brew cask install atom
brew cask install audacity
brew cask install bittorrent-sync
brew cask install calibre
brew cask install eclipse-ide
brew cask install firefox
brew cask install flux
brew cask install gimp
brew cask install google-chrome
brew cask install google-drive
brew cask install google-plus-auto-backup
brew cask install handbrake
brew cask install inkscape
brew cask install iterm2
brew cask install limechat
brew cask install mplayerx
brew cask install no-ip-duc
brew cask install spectacle
brew cask install steam
brew cask install teamspeak-client
brew cask install the-unarchiver
brew cask install torbrowser
brew cask install utorrent
brew cask install vagrant
brew cask install virtualbox
brew cask install xquartz

