# Path to your oh-my-zsh configuration
ZSH=$HOME/.oh-my-zsh

# Set zsh theme
ZSH_THEME="olanmatt"

# Set default zsh user
DEFAULT_USER=`whoami`

# Red dots displayed while waiting for completion
COMPLETION_WAITING_DOTS="true"

# Oh My Zsh plugins
plugins=(git svn brew pip python ruby screen sudo vagrant rvm)

# Source oh-my-zsh
source $ZSH/oh-my-zsh.sh

# Source configuration files
for file in $HOME/.{exports,aliases,functions};do
	[ -r "$file" ] && [ -f "$file" ] && source "$file"
done
unset file
