# Path to your oh-my-zsh configuration.
ZSH=$HOME/.oh-my-zsh

# Set name of the theme to load.
ZSH_THEME="olanmatt"

# Example aliases
# alias zshconfig="mate ~/.zshrc"
# alias ohmyzsh="mate ~/.oh-my-zsh"
for file in $HOME/.{exports,aliases,functions};do
	[ -r "$file" ] && [ -f "$file" ] && source "$file"
done
unset file

# Set to this to use case-sensitive completion
# CASE_SENSITIVE="true"

# Uncomment this to disable bi-weekly auto-update checks
# DISABLE_AUTO_UPDATE="true"

# Uncomment to change how often before auto-updates occur? (in days)
# export UPDATE_ZSH_DAYS=13

# Uncomment following line if you want to disable colors in ls
# DISABLE_LS_COLORS="true"

# Uncomment following line if you want to disable autosetting terminal title.
# DISABLE_AUTO_TITLE="true"

# Uncomment following line if you want to disable command autocorrection
# DISABLE_CORRECTION="true"

# Uncomment following line if you want red dots to be displayed while waiting for completion
# COMPLETION_WAITING_DOTS="true"

# Uncomment following line if you want to disable marking untracked files under
# VCS as dirty. This makes repository status check for large repositories much,
# much faster.
# DISABLE_UNTRACKED_FILES_DIRTY="true"

# Which plugins would you like to load? (plugins can be found in ~/.oh-my-zsh/plugins/*)
# Custom plugins may be added to ~/.oh-my-zsh/custom/plugins/
# Example format: plugins=(rails git textmate ruby lighthouse)
plugins=(git svn brew pip python ruby screen sudo vagrant rvm)

source $ZSH/oh-my-zsh.sh
DEFAULT_USER=`whoami`

# Customize to your needs...
export PATH=$PATH:/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/bin
export GOPATH=$HOME/Documents/go # Add Go path to PATH
# TODO(olanmatt): GOROOT based on OS.
export GOROOT=/usr/local/Cellar/go/1.4.2/libexec # Add Go root to PATH
export PATH="/usr/local/heroku/bin:$PATH" # Add Heroku Toolbelt to PATH
export PATH="$PATH:$HOME/.rvm/bin" # Add RVM to PATH
source /usr/local/bin/virtualenvwrapper.sh # Add virtualenvwrapper to PATH
