# Case-insensitive globbing
shopt -s nocaseglob

# Append to the Bash history file
shopt -s histappend

# Autocorrect for 'cd' path names
shopt -s cdspell

# Auto 'cd' expansion (Bash 4)
shopt -s autocd 2> /dev/null

# Recursive globbing (Bash 4)
shopt -s globstar 2> /dev/null

# Tab completion for many more commands
[ -f /etc/bash_completion ] && source /etc/bash_completion

# Source configuration files
for file in ~/.{exports,aliases,functions}; do
    [ -r "$file" ] && [ -f "$file" ] && source "$file"
done
unset file
